config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  get 'scdash/show'

  resources :tasks
  resources :burndown, only: [:index]
  resources :sprints
  resources :iterations, only: [:index, :show]
  resources :today, only: [:index]
  resources :memes
  resources :sync, only: [:index]
  root 'today#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meme.rb
class Meme < ApplicationRecord
  validates :image, presence: true
  validates :view_date, presence: true

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  before_action :set_meme, only: [:show, :edit, :update, :destroy]

  # GET /memes
  # GET /memes.json
  def index
    @memes = Meme.order(view_date: :desc)
  end

  # GET /memes/1
  # GET /memes/1.json
  def show
  end

  # GET /memes/new
  def new
    @meme = Meme.new
  end

  # GET /memes/1/edit
  def edit
  end

  # POST /memes
  # POST /memes.json
  def create
    @meme = Meme.new(meme_params)

    respond_to do |format|
      if @meme.save
        format.html { redirect_to @meme, :flash => { :success => "Meme was successfully posted." } }
        format.json { render :show, status: :created, location: @meme }
      else
        format.html { redirect_to @meme, :flash => { :error => "You must attach an image!" } }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memes/1
  # PATCH/PUT /memes/1.json
  def update
    respond_to do |format|
      if @meme.update(meme_params)
        format.html { redirect_to @meme, :flash => { :success => "Meme was successfully updated." } }
        format.json { render :show, status: :ok, location: @meme }
      else
        format.html { redirect_to @meme, :flash => { :error => "You must attach an image!" } }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memes/1
  # DELETE /memes/1.json
  def destroy
    @meme.destroy
    respond_to do |format|
      format.html { redirect_to memes_url, notice: 'Meme was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meme
      @meme = Meme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meme_params
      params.require(:meme).permit(:image, :view_date)
    end
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/views/memes/_form.html.erb
<%= simple_form_for @meme do |f| %>
  <% if meme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meme.errors.count, "error") %> prohibited this meme from being saved:</h2>

      <ul>
      <% meme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :image %>
    <%= f.input :view_date, as: :date, :order => [:month, :day, :year] %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/memes/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="card input mb-3 text-center">
        <div class="card-block">
          <h4 class="card-title">Edit Meme</h4>
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <span class="card-text"><%= render 'form', meme: @meme %></span>
            </div>
          </div class="col-md-2"></div>
        </div>
        <span class="card-text"><%= link_to 'Back', memes_path %></span>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/memes/index.html.erb
<div class="page-content">
  <div id="portlet-config" class="modal hide">
    <div class="modal-header">
      <button data-dismiss="modal" class="close" type="button"></button>
      <h3>Widget Settings</h3>
    </div>
    <div class="modal-body"> Widget settings form goes here </div>
  </div>
  <div class="clearfix"></div>
  <div class="content">
  <p id="notice"><%= notice %></p>
    <div class="page-title">
      <h1>Memes</h1>
    </div>

    <div class="text-center">
      <%= link_to 'New Meme', new_meme_path, class: "btn btn-outline-primary" %>
    </div>

    </br>

    <div class="row-fluid">
      <div class="span12">
        <div class="grid simple ">
          <div class="grid-title">
            <h4>Memes <span class="semi-bold">List</span></h4>
            <div class="tools">
              <a href="javascript:;" class="collapse"></a>
              <a href="#grid-config" data-toggle="modal" class="config"></a>
              <a href="javascript:;" class="reload"></a>
              <a href="javascript:;" class="remove"></a>
            </div>
          </div>
          <div class="grid-body ">
            <table class="table table-hover table-condensed" id="example">
              <thead>
                <tr>
                  <th>Options</th>
                  <th>Meme</th>
                  <th>Date to Show Meme</th>
                </tr>
              </thead>
              <tbody>
                <% @memes.each do |meme| %>
                <tr class="even gradeC">
                  <td><%= link_to (fa_icon "eye"), meme %> | <%= link_to (fa_icon "pencil-square"), edit_meme_path(meme) %> | <%= link_to (fa_icon "trash"), meme, method: :delete, data: { confirm: 'Are you sure you want to delete this meme?' } %></td>
                  <td><%= image_tag meme.image.url(:medium) %></td>
                  <td class="center"><%= meme.view_date.strftime("%m-%d-%Y") %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/memes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="card input card-outline-primary mb-3 text-center">
        <div class="card-block">
          <h4 class="card-title">New Meme</h4>
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <span class="card-text"><%= render 'form', meme: @meme %></span>
            </div>
          </div class="col-md-2"></div>
        </div>
        <span class="card-text"><%= link_to 'Back', memes_path %></span>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/memes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="card input mb-3 text-center">
        <%= image_tag @meme.image.url(:medium), class: "card-img-top" %>
        <div class="card-block">
          <h4 class="card-title">Meme for <%= @meme.view_date.strftime("%B %d, %Y") %></h4>
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <span class="card-text"><%= render 'form', meme: @meme %></span>
            </div>
          </div class="col-md-2"></div>
        </div>
        <span class="card-text"><%= link_to "Edit", edit_meme_path(@meme) %> | <%= link_to 'Back', memes_path %></span>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>