config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  get 'scdash/show'

  resources :tasks
  resources :burndown, only: [:index]
  resources :sprints
  resources :iterations, only: [:index, :show]
  resources :today, only: [:index]
  resources :memes
  resources :sync, only: [:index]
  root 'today#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sprint.rb
class Sprint < ApplicationRecord
  has_many :tasks
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  before_action :set_sprint, only: [:show, :edit, :update, :destroy]

  # GET /sprints
  # GET /sprints.json
  def index
    @sprints = Sprint.order(end_date: :desc)
  end

  # GET /sprints/1
  # GET /sprints/1.json
  def show
  end

  # GET /sprints/new
  def new
    @sprint = Sprint.new
  end

  # GET /sprints/1/edit
  def edit
  end

  # POST /sprints
  # POST /sprints.json
  def create
    @sprint = Sprint.new(sprint_params)

    respond_to do |format|
      if @sprint.save
        format.html { redirect_to @sprint, notice: 'Sprint was successfully created.' }
        format.json { render :show, status: :created, location: @sprint }
      else
        format.html { render :new }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sprints/1
  # PATCH/PUT /sprints/1.json
  def update
    respond_to do |format|
      if @sprint.update(sprint_params)
        format.html { redirect_to @sprint, notice: 'Sprint was successfully updated.' }
        format.json { render :show, status: :ok, location: @sprint }
      else
        format.html { render :edit }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sprints/1
  # DELETE /sprints/1.json
  def destroy
    @sprint.destroy
    respond_to do |format|
      format.html { redirect_to sprints_url, notice: 'Sprint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sprint
      @sprint = Sprint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sprint_params
      params.require(:sprint).permit(:name, :start_date, :end_date)
    end
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/views/sprints/_form.html.erb
<%= simple_form_for(@sprint) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :start_date, as: :date, :order => [:month, :day, :year] %>
    <%= f.input :end_date, as: :date, :order => [:month, :day, :year] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sprints/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="card input mb-3 text-center">
        <div class="card-block">
          <h4 class="card-title">Edit Sprint</h4>
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <span class="card-text"><%= render 'form', sprint: @sprint %></span>
            </div>
          </div class="col-md-2"></div>
        </div>
        <span class="card-text"><%= link_to 'Back', sprints_path %></span>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/sprints/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Sprints</h1>

<br>

<%= link_to 'New Sprint', new_sprint_path %>

<table class="table">
  <thead>
    <tr>
      <th>Options</th>
      <th>Sprint Name</th>
      <th>Start date</th>
      <th>End date</th>
    </tr>
  </thead>

  <tbody>
    <% @sprints.each do |sprint| %>
      <tr>
        <td><%= link_to (fa_icon "pencil-square"), edit_sprint_path(sprint) %> | <%= link_to (fa_icon "trash"), sprint, method: :delete, data: { confirm: 'Are you sure you want to delete this Sprint?' } %></td>
        <td><%= sprint.name %></td>
        <td><%= sprint.start_date.strftime("%b %d, %Y") %></td>
        <td><%= sprint.end_date.strftime("%b %d, %Y") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>

app/views/sprints/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="card input card-outline-primary mb-3 text-center">
        <div class="card-block">
          <h4 class="card-title">New Sprint</h4>
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <span class="card-text"><%= render 'form', sprint: @sprint %></span>
            </div>
          </div class="col-md-2"></div>
        </div>
        <span class="card-text"><%= link_to 'Back', sprints_path %></span>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/sprints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sprint.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @sprint.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @sprint.end_date %>
</p>

<%= link_to 'Edit', edit_sprint_path(@sprint) %> |
<%= link_to 'Back', sprints_path %>