config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  get 'scdash/show'

  resources :tasks
  resources :burndown, only: [:index]
  resources :sprints
  resources :iterations, only: [:index, :show]
  resources :today, only: [:index]
  resources :memes
  resources :sync, only: [:index]
  root 'today#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/iteration.rb
class Iteration < ApplicationRecord
  def self.sync_from_api
    RallyApi.sync_iterations
  end
end

app/models/meme.rb
class Meme < ApplicationRecord
  validates :image, presence: true
  validates :view_date, presence: true

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/program.rb
class Program < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
end

app/models/scdash.rb
class Scdash < ApplicationRecord
  def self.app_active
    Parature.redis_active_app_tickets
  end

  def self.app_solved
    Parature.redis_solved_app_tickets
  end

  def self.app_chat
    Parature.solved_app_chat
  end

  def self.rec_active
    Parature.redis_active_rec_tickets
  end

  def self.rec_solved
    Parature.redis_solved_rec_tickets
  end

  def self.rec_chat
    Parature.solved_rec_chat
  end

  def self.team_member_ticket_counts
    Parature.solved_tickets_by_team_member
  end

end

app/models/sprint.rb
class Sprint < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :sprint
  belongs_to :project, primary_key: :assigned_id

  def self.intro
    JsonFiles.task_index_intro
  end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  before_action :set_meme, only: [:show, :edit, :update, :destroy]

  # GET /memes
  # GET /memes.json
  def index
    @memes = Meme.order(view_date: :desc)
  end

  # GET /memes/1
  # GET /memes/1.json
  def show
  end

  # GET /memes/new
  def new
    @meme = Meme.new
  end

  # GET /memes/1/edit
  def edit
  end

  # POST /memes
  # POST /memes.json
  def create
    @meme = Meme.new(meme_params)

    respond_to do |format|
      if @meme.save
        format.html { redirect_to @meme, :flash => { :success => "Meme was successfully posted." } }
        format.json { render :show, status: :created, location: @meme }
      else
        format.html { redirect_to @meme, :flash => { :error => "You must attach an image!" } }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memes/1
  # PATCH/PUT /memes/1.json
  def update
    respond_to do |format|
      if @meme.update(meme_params)
        format.html { redirect_to @meme, :flash => { :success => "Meme was successfully updated." } }
        format.json { render :show, status: :ok, location: @meme }
      else
        format.html { redirect_to @meme, :flash => { :error => "You must attach an image!" } }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memes/1
  # DELETE /memes/1.json
  def destroy
    @meme.destroy
    respond_to do |format|
      format.html { redirect_to memes_url, notice: 'Meme was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meme
      @meme = Meme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meme_params
      params.require(:meme).permit(:image, :view_date)
    end
end

app/controllers/sync_controller.rb
class SyncController < ApplicationController
  def index
    #Iteration.sync_from_api

    #redirect_to iterations_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.order(historical_date: :desc)

    @intro = Task.intro
    @intro_text = JSON.parse(@intro)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, :flash => { :success => "Task was successfully created." } }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:sprint_id, :project_id, :historical_date, :task_hours)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    {
      :success => "alert-success",
      :error => "alert-danger",
      :alert => "alert-warning",
      :notice => "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/burndown_helper.rb
module BurndownHelper
end

app/helpers/iterations_helper.rb
module IterationsHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/helpers/scdash_helper.rb
module ScdashHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/helpers/sync_helper.rb
module SyncHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/today_helper.rb
module TodayHelper
end

app/views/layouts/_navbar.html.erb
  <!-- BEGIN TOP NAVIGATION BAR -->
  <div class="header navbar inner-inverse">
    <div class="navbar-inner">
      <div class="header-seperation">
        <ul class="nav pull-left notifcation-center visible-xs visible-sm">
          <li class="dropdown">
            <a href="#main-menu" data-webarch="toggle-left-side">
              <i class="material-icons">menu</i>
            </a>
          </li>
        </ul>
      <!-- BEGIN LOGO -->
      <%= image_tag("https://s3-us-west-2.amazonaws.com/kpl.assets/WhiteonMaroon.jpg", width: '160') %>
      <!-- END LOGO -->
        <ul class="nav pull-right notifcation-center">
          <li class="dropdown hidden-xs hidden-sm">
            <a href="" class="dropdown-toggle active" data-toggle="">
              <i class="material-icons">home</i>
            </a>
          </li>
          <li class="dropdown hidden-xs hidden-sm">
            <a href="" class="dropdown-toggle">
              <i class="material-icons">email</i><span class="badge bubble-only"></span>
            </a>
          </li>
          <li class="dropdown visible-xs visible-sm">
            <a href="#" data-webarch="toggle-right-side">
              <i class="material-icons">chat</i>
            </a>
          </li>
        </ul>
      </div>
    <!-- END RESPONSIVE MENU TOGGLER -->
      <div class="header-quick-nav">
      <!-- BEGIN TOP NAVIGATION MENU -->
        <div class="pull-left">
          <ul class="nav quick-section">
            <li class="quicklinks m-r-10">
              <%= link_to( content_tag(:i, "menu", class: "material-icons"), "javascript:;", id: "layout-condensed-toggle") %>
          </li>
        </ul>
        <ul class="nav quick-section">
          <li class="quicklinks  m-r-10">
            <a href="#" class="">
              <i class="material-icons">refresh</i>
            </a>
          </li>
          <li class="quicklinks">
            <a href="#" class="">
              <i class="material-icons">apps</i>
            </a>
          </li>
        </ul>
      </div>
      <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END TOP NAVIGATION MENU -->
  </div>
  <!-- END TOP NAVIGATION BAR -->
</div>

app/views/layouts/_sidebar.html.erb
<!-- BEGIN SIDEBAR -->
<div class="page-sidebar " id="main-menu">
  <!-- BEGIN MINI-PROFILE -->
  <div class="page-sidebar-wrapper scrollbar-dynamic" id="main-menu-wrapper">
    <div class="user-info-wrapper sm">
      <div class="profile-wrapper sm">
        <%= image_tag ("profiles/avatar.png"), width: '69', height: '69' %>
        <div class="availability-bubble online"></div>
      </div>
      <div class="user-info sm">
        <div class="username">Kevin <span class="semi-bold">Leahey</span></div>
        <div class="status">This site is dashing...</div>
      </div>
    </div>
    <!-- END MINI-PROFILE -->
    <!-- BEGIN SIDEBAR MENU -->
    <p class="menu-title sm">BROWSE <span class="pull-right"><a href="javascript:;"><i class="material-icons">refresh</i></a></span></p>
    <ul>
      <li>
        <%= link_to today_index_path, class: "start active" do %>
          <i class="material-icons">home</i>
        <% end %>
      </li>
      <li class="">
        <a href="javascript:;"> <i class="material-icons">more_horiz</i> <span class="title">Dashboards</span> <span class=" arrow"></span> </a>
        <ul class="sub-menu">
          <li>
            <%= link_to ("Solutions Center"), scdash_show_path %>
          </li>
        </ul>
      </li>
      <li class="hidden-lg hidden-md hidden-xs" id="more-widgets">
        <a href="javascript:;"> <i class="material-icons"></i></a>
        <ul class="sub-menu">
          <li class="side-bar-widgets">
            <p class="menu-title sm">FOLDER <span class="pull-right"><a href="#" class="create-folder"><i class="material-icons">add</i></a></span></p>
            <ul class="folders">
              <li>
                <a href="#">
                  <div class="status-icon green"></div>
                  My quick tasks </a>
              </li>
            </ul>
            <p class="menu-title">PROJECTS </p>
            <div class="status-widget">
              <div class="status-widget-wrapper">
                <div class="title">Freelancer<a href="#" class="remove-widget"><i class="material-icons">close</i></a></div>
                <p>Redesign home page</p>
              </div>
            </div>
          </li>
        </ul>
      </li>
    </ul>
    <div class="side-bar-widgets">
      <p class="menu-title sm">FOLDER <span class="pull-right"><a href="#" class="create-folder"> <i class="material-icons">add</i></a></span></p>
      <ul class="folders">
        <li>
          <a href="#">
            <div class="status-icon green"></div>
            My quick tasks </a>
        </li>
      </ul>
      <p class="menu-title">PROJECTS </p>
      <div class="status-widget">
        <div class="status-widget-wrapper">
          <div class="title">Freelancer<a href="#" class="remove-widget"><i class="material-icons">close</i></a></div>
          <p>Redesign home page</p>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
    <!-- END SIDEBAR MENU -->
  </div>
</div>
<a href="#" class="scrollup">Scroll</a>
<div class="footer-widget">
  <div class="progress transparent progress-small no-radius no-margin">
    <div class="progress-bar progress-bar-success animate-progress-bar" data-percentage="79%" style="width: 79%;"></div>
  </div>
  <div class="pull-right">
    <div class="details-status"> <span class="animate-number" data-value="86" data-animation-duration="560">86</span>% </div>
    <a href="lockscreen.html"><i class="material-icons">power_settings_new</i></a></div>
</div>
<!-- END SIDEBAR -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Devdash</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
  </head>

  <body class="">
    <!-- BEGIN HEADER -->
    <div class="header navbar navbar-inverse ">
      <%= render "layouts/navbar" %>
    </div>
    <!-- END HEADER -->

    <!-- BEGIN CONTENT -->
    <div class="page-container row-fluid">
      <%= render "layouts/sidebar" %>
      
      <%= yield %>
    </div>
    <!-- END CONTENT -->
  </body>
</html>